#!/bin/bash

INFO="
Block the screen by disabling all input devices.

Usage:
    blockscreen <minutes>
"

if [ "x$1" = x ]; then
    echo "$INFO" 1>&2
    exit 1
fi

SLEEP=$(($1 * 60)) || exit 1

function block_all() {
    xinput list --id-only | xargs -n 1 xinput disable >/dev/null 2>&1
    return 0
}

function unblock_all() {
    xinput list --id-only | xargs -n 1 xinput enable >/dev/null 2>&1
    return 0
}

trap "" HUP
trap unblock_all EXIT
block_all || exit 1

xset dpms force off || true
sleep $SLEEP || true

unblock_all || exit 1
trap "" EXIT

play -q -n synth 0.2 sin C5 sin G5 sin C6 delay 0.0 0.2 0.4 &
