#!/bin/bash

INFO="
Check to what degree each 100,000 byte chunk of a file can
be compressed with gzip.

Usage:
    data-density <file>
"

if [ ! -e "$1" ]; then
    echo "$INFO" 1>&2
    exit 1
fi

TMPDIR=$(mktemp -d) || exit 1
trap "rm -rf $TMPDIR" EXIT

while dd status=none bs=100000 count=1 of="$TMPDIR/chunk"; do
    SIZE1=$(stat -c%s "$TMPDIR/chunk")
    if [ "x$SIZE1" = x100000 ]; then
        SIZE2=$(gzip --fast < "$TMPDIR/chunk" | wc -c)
        FACTOR=$((($SIZE2 * 10) / $SIZE1))
        [ $FACTOR -lt 10 ] || FACTOR=9
        echo -n $FACTOR
    elif [ "$SIZE1" -gt 0 ]; then
        echo -n .
        break
    else
        break
    fi
done < "$1"
echo
