#!/bin/bash

INFO="
Encode an audio file to OGG format, or copy the stream if possible.

Usage:
    ifneeded2ogg <infile> [ <outfile.ogg> ]
    ifneeded2ogg --force <infile> [ <outfile.ogg> ]
"

FORCE=
if [ "x$1" = x--force ]; then
    FORCE=1
    shift
fi

INFILE="$1"
OUTFILE="$2"

if [ "x$INFILE" = x -o ! -f "$INFILE" ]; then
    echo "$INFO" 1>&2
    exit 1
fi

if [ "x$OUTFILE" = x ]; then
    OUTFILE=$(echo "$INFILE" | sed -r -e 's/\.([a-zA-Z0-9]{2,5})$//').ogg
fi

if [ "x$FORCE" != x1 ] && [ -e "$OUTFILE" ]; then
    echo "Error: file '$OUTFILE' already exists" 1>&2
    exit 1
fi

TMPDIR=$(mktemp -d) || exit 1
trap "rm -rf $TMPDIR" EXIT

if ! ffmpeg -i "$INFILE" -vn -acodec copy "$TMPDIR/out.ogg" ; then
    ffmpeg -i "$INFILE" -vn "$TMPDIR/out.wav" || exit 1
    oggenc -q 5 "$TMPDIR/out.wav" -o "$TMPDIR/out.ogg" || exit 1
fi

cat "$TMPDIR/out.ogg" > "$OUTFILE" || exit 1
