#!/bin/bash

INFO="
Convert image brightness to alpha channel.

Usage:
    image-to-mask
"

if [ "x$1" = x ]; then
    echo "$INFO" 1>&2
    exit 1
fi

INPUT="$1"
shift

exec batch-convert "$INPUT" png \
    convert - \
    -strip \
    -background white -flatten -alpha off -colorspace gray \
    -negate -alpha copy -channel rgb -fx 0 \
    "$@" png32:-
