#!/bin/bash

INFO="
Clean up black-on-white images.

Usage:
    image-clear-scan
"

if [ "x$1" = x ]; then
    echo "$INFO" 1>&2
    exit 1
fi

INPUT="$1"
shift

exec batch-convert "$INPUT" png \
    convert - \
    -strip \
    -background white -flatten -alpha off -colorspace gray \
    -negate \
    \( -clone 0 -resize 10% -gaussian-blur 0x10 -level 0,90% -resize 1000% \) \
    -compose minus_src -composite \
    -contrast-stretch '50%x2%' \
    -negate \
    "$@" png:-
