#!/bin/bash

INFO="
Start vncserver on a remote host, set up ssh tunneling,
and connect to the session using vncviewer.

Usage:
    sshvnc <ssh options>
"

if [ "x$1" = x ]; then
    echo "$INFO" 1>&2
    exit 1
fi

TMPDIR=$(mktemp -d) || exit 1
trap "rm -rf $TMPDIR" EXIT

RESOLUTION=$(xinfo r) || exit 1
touch "$TMPDIR/out" || exit 1

CREATE_PASSWD_FILE='[ -f .vnc/passwd ] || ( echo -n '\
'$'"'"'\x49\x40\x15\xf9\xa3\x5e\x8b\x22'"'"' > '\
'.vnc/passwd && chmod 0600 .vnc/passwd )'

RUN_SERVER='vncserver -geometry '"$RESOLUTION"' -depth 24 '\
'-alwaysshared -dpi 96 -localhost :1 >/dev/null 2>&1 &'

( \
    echo 'cd || exit 1'; \
    echo 'mkdir -p .vnc || exit 1'; \
    echo "$CREATE_PASSWD_FILE || exit 1"; \
    echo "$RUN_SERVER"; \
    echo 'test -f .vnc/passwd && cat .vnc/passwd'; \
    while test $(stat -c%s "$TMPDIR/out") = 0; do sleep 1; done; \
    echo "Connecting..." 1>&2; \
    vncviewer 127.0.0.1:6900 -passwd "$TMPDIR/out" 1>&2 \
) | ssh "$@" -L 6900:localhost:5901 > "$TMPDIR/out"
ret=$?

exit $ret
