#!/bin/bash

INFO="
Run 'latexmk' while keeping all the temporary files in /tmp.

Usage:
    tex2pdf  [ latexmk options ] <input.tex>
"

if [ "x$1" = x -o ! -e "${!#}" ]; then
    echo "$INFO" 1>&2
    exit 1
fi

strip_extension() {
    sed -r -e 's/\.([a-zA-Z0-9]{2,5})$//' <<< "$1" || return 1
    return 0
}

INPUT_FILE=$(readlink -e "${!#}") || exit 1
INPUT_DIR=$(readlink -m "$INPUT_FILE/..") || exit 1
OUTPUT_FILE=$(strip_extension "$INPUT_FILE").pdf

TMPDIR=$(mktemp -d) || exit 1
trap "rm -rf $TMPDIR" EXIT
cd "$TMPDIR" || exit 1

cp "$INPUT_FILE" "document.tex" || exit 1

ls "$INPUT_DIR" | grep -ivE '\.(md|pdf)$' | while IFS= read -r f; do
    ln -s "$INPUT_DIR/$f" . >/dev/null
done

latexmk -pdf "${@:1:${#}-1}" document.tex </dev/null || exit 1

cp document.pdf "$OUTPUT_FILE" || exit 1
